### ISSUE TITLE
signup action question

### ISSUE THREAD

**Issue by v-anyukov** [VonIobro/my_meteor_mantra#4]
[Here](https://github.com/VonIobro/my_meteor_mantra/blob/master/client/modules/core/actions/accounts.js#L20) we have `const usernameAlreadyExists = Meteor.users.findOne({ username });` This implies the presence of publications and subscriptions to all users. Why do not we use the method, something like `Meteor.call('checkUserExists', username, (err, res) => { //do next stuff})`? In this case we dont have troubles with publishing users, security, performance etc.

PS Sorry for my english. I really hope my message is clear enough.

**Comment by VonIobro** [comment]
Hi @v-anyukov . Thanks for the feedback. Your message was perfectly clear, don't worry about your English^^.

I've updated the signup process with [this commit](https://github.com/VonIobro/my_meteor_mantra/commit/7f16e0eb4a0f8da5ffea7aea6e8d5a13872b41c1)

I'm always open to feedback, thanks!

**Comment by v-anyukov** [comment]
Hi
I've read a little and it looks like, our test user name is not needed at all. Accordin [this](http://docs.meteor.com/api/passwords.html#Accounts-createUser) Accounts.createUser throws error if username or email exists, so we dont need to check username, just catch error in createUser callback.

**Comment by zobroj** [comment]
Aha. Thanks for letting me know. I changed the code to rely on Accounts.createUser to check username.
